chore: adjust Dependabot configuration
jenstroeger/python-package-template pull request #183
Opened 2022-04-26 22:16 UTC by behnazh

Changes the Dependabot configuration to run the checks weekly instead of daily. Also changes the `fix` commit message scopes to `chore`.

2022-04-26 22:22 UTC, jenstroeger requested changes
Looks good, except the updated `src/package/__init__.py` file 😉

2022-04-26 22:26 UTC, behnazh commented
> Looks good, except the updated `src/package/__init__.py` file wink

That happened because `staging` is not rebased on `main` I think.

2022-04-26 22:47 UTC, jenstroeger commented
You’re right, done!

2022-05-04 22:29 UTC, jenstroeger approved these changes

2022-05-05 06:24 UTC, merged